spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    password: 
    username: root
    url: jdbc:mysql://localhost:3306/ms_db_fornecedor
  jpa:
    hibernate:
      ddl-auto: update
